# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('followers', models.IntegerField(blank=True, null=True)),
                ('tweet', models.CharField(max_length=200)),
                ('retweets', models.IntegerField(blank=True, null=True)),
                ('favourited', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('screen_name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
