# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
