# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0002_remove_tweet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweet', to='miner.User'),
        ),
    ]
